matrix:
  include:
  - language: c

	before_install:
		- wget http://downloads.sourceforge.net/project/cunit/CUnit/2.1-2/CUnit-2.1-2-src.tar.bz2
		- tar -xvjpf CUnit-2.1-2-src.tar.bz2
		- cd CUnit-2.1-2
		- ./configure --prefix=$TRAVIS_BUILD_DIR
		- make
		- make install
		- export C_INCLUDE_PATH=$TRAVIS_BUILD_DIR/include:$C_INCLUDE_PATH
		- export LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LIBRARY_PATH
		- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
		- cd ..
		- cd c

	script:
		- make test

  - language: cpp

	before_install:
		- wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
		- unzip gtest-1.7.0.zip 
		- cd gtest-1.7.0/
		- ./configure --prefix=$TRAVIS_BUILD_DIR --with-pthreads=no
		- make
		- mkdir $TRAVIS_BUILD_DIR/include/
		- cp -r include/gtest $TRAVIS_BUILD_DIR/include
		- mkdir $TRAVIS_BUILD_DIR/lib/
		- cp lib/.libs/* $TRAVIS_BUILD_DIR/lib/
		- cd ..
		- export CPLUS_INCLUDE_PATH=$TRAVIS_BUILD_DIR/include:$CPLUS_INCLUDE_PATH
		- export LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LIBRARY_PATH
		- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
		- cd cpp

	script:
		- make googletest
		
  - language: java

	jdk:
		- oraclejdk8
		- openjdk7

	before_install:
		- cd java		
		
#NOTE: Pull Request builds do not trigger email notifications.
notifications:
  email:
    recipients:
     - chester.fan@vertivco.com
    on_success: always
    on_failure: always

#if normal build, ${TRAVIS_PULL_REQUEST} = false
#if pull request, ${TRAVIS_PULL_REQUEST} = pull request's number

#- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ABC || XYZ'

